apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/mannanjaffery/civicpulse-platform/backend
    newName: ghcr.io/mannanjaffery/civicpulse-platform/backend
    newTag: latest
  - name: ghcr.io/mannanjaffery/civicpulse-platform/frontend
    newName: ghcr.io/mannanjaffery/civicpulse-platform/frontend
    newTag: latest
