apiVersion: v1
kind: Secret
metadata:
  name: civicpulse-secret
  namespace: civicpulse
type: Opaque
stringData:
  POSTGRES_USER: "civicpulse_user"
  POSTGRES_PASSWORD: "civicpulse_password_placeholder"
  DATABASE_URL: "postgresql://civicpulse_user:civicpulse_password_placeholder@postgres:5432/civicpulse_db"
  GROQ_API_KEY: "groq_api_key_placeholder"
  GEMINI_API_KEY: "gemini_api_key_placeholder"
